CUDA_VISIBLE_DEVICES=0 swift sft \
    --torch_dtype 'bfloat16' \
    --model '/home/pico/model/internlm3-8b-instruct' \
    --model_type 'internlm3' \
    --template 'internlm2' \
    --dataset 'data/train_hepatobiliary.jsonl' \
    --max_length '1024' \
    --init_weights 'True' \
    --learning_rate '1e-4' \
    --gradient_accumulation_steps '16' \
    --eval_steps '500' \
    --truncation_strategy 'delete' \
    --report_to 'tensorboard'  \
    --add_version False \
    --output_dir /home/pico/myCodes/llm/output/output/internlm3-8b-instruct/v0-20250603-190933 \
    --logging_dir /home/pico/myCodes/llm/output/output/internlm3-8b-instruct/v0-20250603-190933/runs \
    --ignore_args_error True \
    --resume_from_checkpoint /home/pico/myCodes/llm/output/output/internlm3-8b-instruct/v0-20250603-190933/checkpoint-500